apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "multi-stage.serviceAccountName" . }}
  annotations:
  {{- range $k,$v := (lookup "v1" "Namespace" "" "kube-system").metadata.labels }}
    {{$k}}: {{$v}}
  {{- end }}
data:
  ca.crt: {{ dig "data" "ca\\.crt" "ca\\.crt" (lookup "v1" "ConfigMap" "kube-root-ca.crt" (printf "%s" .Release.Namespace)) }}
