apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "multi-stage.serviceAccountName" . }}
  labels:
  {{- range $k,$v := (lookup "v1" "Namespace" "" "kube-system").metadata.labels }}
    {{$k}}: {{$v}}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  a: b
