apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "multi-stage.serviceAccountName" . }}
  annotations:
  {{- range $k,$v := (lookup "v1" "Namespace" "" "kube-system").metadata.labels }}
    {{$k}}: {{$v}}
  {{- end }}
data:
  a: b
