apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "multi-stage.serviceAccountName" . }}
data:
  ca.crt: |
    {{- dig "data" "ca.crt" "unknown" (lookup "v1" "Secret" (printf "%s" .Release.Namespace) "multi-stage-apiserver-cert") | nindent 4 }}
