{{- $caCrt := "" }}
{{- $serverCrt := "" }}
{{- $serverKey := "" }}
{{- $ca := genCA "ca" 3650 }}
{{- $cn := include "multi-stage.fullname" . -}}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $server := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}
{{- $caCrt =  b64enc $ca.Cert }}
{{- $serverCrt = b64enc $server.Cert }}
{{- $serverKey = b64enc $server.Key }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "multi-stage.fullname" . }}-apiserver-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "multi-stage.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/resource-policy": keep
type: kubernetes.io/tls
data:
  ca.crt: {{ $caCrt }}
  tls.crt: {{ $serverCrt }}
  tls.key: {{ $serverKey }}
